// simple/svelte-simple-crud/frontend/src/lib/components/common/Button.svelte
<!-- src/lib/components/common/Button.svelte -->
<script lang="ts">
	type ButtonVariant = 'primary' | 'secondary' | 'danger' | 'ghost' | 'outline';
	type ButtonSize = 'sm' | 'md' | 'lg' | 'icon';

	interface Props {
		variant?: ButtonVariant;
		size?: ButtonSize;
		class?: string;
		disabled?: boolean;
		loading?: boolean;
		type?: 'button' | 'submit' | 'reset';
		onclick?: (event: MouseEvent) => void;
		children?: any;
		icon?: string;
		iconOnly?: boolean;
	}

	let {
		variant = 'primary',
		size = 'md',
		class: className = '',
		disabled = false,
		loading = false,
		type = 'button',
		onclick,
		children,
		icon,
		iconOnly = false,
		...rest
	}: Props = $props();

	// Base button styles that always apply
	const baseStyles = 'inline-flex items-center justify-center font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 rounded-md';

	// Variant styles
	const variantStyles = {
		primary: 'bg-blue-600 text-white hover:bg-blue-700 active:bg-blue-800 shadow-sm',
		secondary: 'bg-neutral-600 text-white hover:bg-neutral-700 active:bg-neutral-800 shadow-sm',
		danger: 'bg-red-600 text-white hover:bg-red-700 active:bg-red-800 shadow-sm',
		ghost: 'bg-neutral-700 text-neutral-200 hover:bg-neutral-600 hover:text-white',
		outline: 'border border-neutral-600 bg-transparent text-neutral-200 hover:bg-neutral-700 hover:text-white'
	};

	// Size styles
	const sizeStyles = {
		sm: iconOnly ? 'h-8 w-8 p-0' : 'h-8 px-3 text-sm',
		md: iconOnly ? 'h-10 w-10 p-0' : 'h-10 px-4 py-2',
		lg: iconOnly ? 'h-12 w-12 p-0' : 'h-12 px-6 py-3 text-lg',
		icon: 'h-10 w-10 p-0'
	};

	// Combine all styles
	const buttonClasses = `${baseStyles} ${variantStyles[variant]} ${sizeStyles[size]} ${className}`;

	function handleClick(event: MouseEvent) {
		if (disabled || loading) {
			event.preventDefault();
			return;
		}
		onclick?.(event);
	}
</script>

<button
	{type}
	class={buttonClasses}
	{disabled}
	onclick={handleClick}
	{...rest}
>
	{#if loading}
		<svg class="animate-spin h-4 w-4 {children ? 'mr-2' : ''}" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
			<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
			<path class="opacity-75" fill="currentColor" d="m4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
		</svg>
	{:else if icon && !children}
		<!-- Icon only button -->
		{#if icon === 'Plus'}
			<svg class="h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
			</svg>
		{:else if icon === 'Pencil'}
			<svg class="h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
			</svg>
		{:else if icon === 'Trash'}
			<svg class="h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
			</svg>
		{:else if icon === 'Save'}
			<svg class="h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
			</svg>
		{/if}
	{:else if icon && children}
		<!-- Button with icon and text -->
		{#if icon === 'Plus'}
			<svg class="h-4 w-4 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
			</svg>
		{:else if icon === 'Save'}
			<svg class="h-4 w-4 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
			</svg>
		{/if}
		{@render children?.()}
	{:else}
		<!-- Text only button -->
		{@render children?.()}
	{/if}
</button>

// crud-starter-pickard-apps/react/crud-app/frontend/src/components/common/Button.tsx
import { forwardRef, ButtonHTMLAttributes, useMemo, useCallback } from 'react';
import Icon from './Icon';

type ButtonVariant = 'primary' | 'secondary' | 'danger' | 'text' | 'stealth';
type ButtonSize = 'xs' | 'sm' | 'md' | 'lg' | 'icon';

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  fullWidth?: boolean;
  icon?: string;
  iconClass?: string;
  iconOnly?: boolean;
  iconPosition?: 'left' | 'right';
  loading?: boolean;
  href?: string;
  target?: string;
  rel?: string;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({
    variant = 'primary',
    size = 'md',
    className = '',
    fullWidth = false,
    icon,
    iconClass,
    iconOnly = false,
    iconPosition = 'left',
    disabled = false,
    loading = false,
    children,
    onClick,
    ...props
  }, ref) => {
    const baseClasses = useMemo(() => {
      let classes = 'inline-flex items-center justify-center font-medium transition-colors duration-150 rounded-sm focus:outline-none focus:ring-1 focus:ring-offset-0 focus:ring-opacity-30';

      if (loading) {
        classes += ' cursor-default';
      } else if (disabled) {
        classes += ' opacity-60 cursor-not-allowed';
      } else {
        classes += ' cursor-pointer';
      }
      return classes;
    }, [loading, disabled]);

    const variantClasses = useMemo(() => ({
      'primary': 'bg-blue-600 text-white hover:bg-blue-700 focus:ring-blue-500/30',
      'secondary': 'bg-neutral-700/80 text-neutral-200 hover:bg-neutral-600 focus:ring-neutral-500/30',
      'danger': 'bg-red-600 text-white hover:bg-red-700 focus:ring-red-500/30',
      'text': 'bg-transparent text-neutral-300 hover:bg-neutral-700/50 focus:ring-blue-500/30',
      'stealth': 'bg-transparent text-neutral-400 hover:text-neutral-200 hover:bg-neutral-700/60 focus:ring-blue-500/30 p-1.5',
    }[variant]), [variant]);

    const effectiveIconOnly = useMemo(() => 
      iconOnly || (!!icon && !children && !loading), 
      [iconOnly, icon, children, loading]
    );

    const sizeClasses = useMemo(() => {
      if (effectiveIconOnly || size === 'icon') {
        return ({
          'xs': 'p-1',
          'sm': 'p-1.5',
          'md': 'p-2',
          'lg': 'p-2.5',
          'icon': 'p-2',
        }[size === 'icon' ? 'icon' : size]) || 'p-2';
      }
      return ({
        'xs': 'text-xs px-2.5 py-1 gap-1',
        'sm': 'text-sm px-3 py-1.5 gap-1.5',
        'md': 'text-base px-4 py-2 gap-2',
        'lg': 'text-lg px-5 py-2.5 gap-2.5',
      }[size]) || 'text-base px-4 py-2 gap-2';
    }, [effectiveIconOnly, size]);

    const iconSizeMap: Record<Exclude<ButtonSize, 'icon'>, number> = { xs: 14, sm: 16, md: 18, lg: 20 };
    const iconSize = size === 'icon' ? 20 : (iconSizeMap[size as Exclude<ButtonSize, 'icon'>] ?? 18);

    const widthClass = fullWidth ? 'w-full' : '';

    const orderClasses = useMemo(() => {
      if (!icon || !children || loading || effectiveIconOnly) return { icon: '', slot: '' };
      return iconPosition === 'left'
        ? { icon: 'order-first', slot: 'order-last' }
        : { icon: 'order-last', slot: 'order-first' };
    }, [icon, children, loading, effectiveIconOnly, iconPosition]);

    const handleClick = useCallback((event: React.MouseEvent<HTMLButtonElement>) => {
      if (disabled || loading) {
        event.preventDefault();
        return;
      }
      onClick?.(event);
    }, [disabled, loading, onClick]);

    return (
      <button
        ref={ref}
        disabled={disabled || loading}
        className={`${baseClasses} ${variantClasses} ${sizeClasses} ${widthClass} ${className}`}
        onClick={handleClick}
        {...props}
      >
        {loading ? (
          <>
            <Icon name="Loader" size={iconSize} className={`animate-spin ${iconClass || ''}`} />
            {children && !effectiveIconOnly && (
              <span className={`${orderClasses.slot} opacity-70`}>{children}</span>
            )}
          </>
        ) : (
          <>
            {icon && (
              <Icon name={icon} size={iconSize} className={`${orderClasses.icon} ${iconClass || ''}`} />
            )}
            {children && !effectiveIconOnly && (
              <span className={orderClasses.slot}>
                {children}
              </span>
            )}
          </>
        )}
      </button>
    );
  }
);

Button.displayName = 'Button';

export default Button;
