// crud-starter-pickard-apps/svelte/crud-app-sqlite-tanstack-shadcn-svelte-vite/src/lib/components/layout/MainLayout.svelte
<!-- src/lib/components/layout/MainLayout.svelte -->
<script lang="ts">
  import AppSidebar from '$lib/components/layout/AppSidebar.svelte';
  import TopBar from '$lib/components/layout/TopBar.svelte';

  export let onNavigate: (path: string) => void;
</script>

<div class="flex min-h-screen bg-background text-foreground">
  <AppSidebar on:navigate={(e) => onNavigate(e.detail)} />
  <div class="flex-1 max-w-5xl mx-auto p-fluid-6">
    <TopBar on:navigate={(e) => onNavigate(e.detail)} />
    <slot />
  </div>
</div>

// crud-starter-pickard-apps/vue/crud-app-sqlite-tanstack-shadcn-nuxt/app/layouts/MainLayout.vue
<script setup lang="ts">
import AppSidebar from "@/components/layout/AppSidebar.vue";
import TopBar from "@/components/layout/TopBar.vue";
</script>

<template>
    <!-- Layout as grid, matching Vue codebase -->
    <div class="grid min-h-screen" style="grid-template-columns: var(--sidebar-width) 1fr">
        <AppSidebar />
        <main class="min-w-0 overflow-y-auto">
            <div class="p-fluid-4 md:p-fluid-6 lg:p-fluid-8">
                <TopBar />
                <slot />
            </div>
        </main>
    </div>
</template>
