// crud-starter-pickard-apps/svelte/crud-app-sqlite-tanstack-shadcn-svelte-vite/src/lib/components/ui/button/Button.svelte
<script lang="ts">
  import { cn } from "$lib/utils.js";
  import type { ButtonHTMLAttributes } from "svelte/elements";
  import { cva, type VariantProps } from "class-variance-authority";

  const buttonVariants = cva(
    "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
    {
      variants: {
        variant: {
          default: "bg-primary text-primary-foreground hover:bg-primary/90",
          destructive:
            "bg-destructive text-destructive-foreground hover:bg-destructive/90",
          outline:
            "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
          secondary:
            "bg-secondary text-secondary-foreground hover:bg-secondary/80",
          ghost: "hover:bg-accent hover:text-accent-foreground",
          link: "text-primary underline-offset-4 hover:underline",
        },
        size: {
          default: "h-10 px-4 py-2",
          sm: "h-9 rounded-md px-3",
          lg: "h-11 rounded-md px-8",
          icon: "h-10 w-10",
        },
      },
      defaultVariants: {
        variant: "default",
        size: "default",
      },
    }
  );

  type Props = ButtonHTMLAttributes & {
    variant?: VariantProps<typeof buttonVariants>["variant"];
    size?: VariantProps<typeof buttonVariants>["size"];
  };

  export let variant: Props["variant"] = "default";
  export let size: Props["size"] = "default";
  let className: Props["class"] = undefined;
  let restProps: $restProps;

  $: buttonClass = cn(buttonVariants({ variant, size, className }));
</script>

<button
  class={buttonClass}
  {...restProps}
  on:click
  on:keydown
  on:keyup
  on:focus
  on:blur
  on:mouseenter
  on:mouseleave
  on:paste
>
  <slot />
</button>

// crud-starter-pickard-apps/crud-app-sqlite-tanstack-shadcn/frontend/src/components/common/Button.tsx
import { forwardRef, ButtonHTMLAttributes, useMemo, useCallback } from 'react';
import Icon from './Icon';

type ButtonVariant = 'primary' | 'secondary' | 'danger' | 'text' | 'stealth' | 'ghost' | 'default';
type ButtonSize = 'xs' | 'sm' | 'md' | 'lg' | 'icon';

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  fullWidth?: boolean;
  icon?: string;
  iconClass?: string;
  iconOnly?: boolean;
  iconPosition?: 'left' | 'right';
  loading?: boolean;
  href?: string;
  target?: string;
  rel?: string;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({
    variant = 'primary',
    size = 'md',
    className = '',
    fullWidth = false,
    icon,
    iconClass,
    iconOnly = false,
    iconPosition = 'left',
    disabled = false,
    loading = false,
    children,
    onClick,
    ...props
  }, ref) => {
    const baseClasses = useMemo(() => {
      let classes = 'inline-flex items-center justify-center font-button transition-[--button-transition] rounded-button focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2';

      if (loading) {
        classes += ' cursor-default';
      } else if (disabled) {
        classes += ' opacity-50 cursor-not-allowed pointer-events-none';
      } else {
        classes += ' cursor-pointer';
      }
      return classes;
    }, [loading, disabled]);

    const variantClasses = useMemo(() => ({
      'default': 'bg-primary text-text-inverse hover:bg-primary-hover active:bg-primary-active',
      'primary': 'bg-primary text-text-inverse hover:bg-primary-hover active:bg-primary-active',
      'secondary': 'bg-surface-active text-text-primary hover:bg-surface-hover border border-border',
      'danger': 'bg-danger text-text-inverse hover:bg-danger-hover focus:ring-danger',
      'text': 'bg-transparent text-text-primary hover:bg-surface-hover focus:ring-primary',
      'stealth': 'bg-transparent text-text-muted hover:text-text-primary hover:bg-surface-hover focus:ring-primary btn-icon-sm',
      'ghost': 'bg-transparent hover:bg-surface-hover text-text-primary',
    }[variant]), [variant]);

    const effectiveIconOnly = useMemo(() => 
      iconOnly || (!!icon && !children && !loading), 
      [iconOnly, icon, children, loading]
    );

    const sizeClasses = useMemo(() => {
      if (effectiveIconOnly || size === 'icon') {
        return ({
          'xs': 'btn-icon-xs',
          'sm': 'btn-icon-sm',
          'md': 'btn-icon-md',
          'lg': 'btn-icon-lg',
          'icon': 'btn-icon-md',
        }[size === 'icon' ? 'icon' : size]) || 'btn-icon-md';
      }
      return ({
        'xs': 'btn-xs',
        'sm': 'btn-sm',
        'md': 'btn-md',
        'lg': 'btn-lg',
      }[size]) || 'btn-md';
    }, [effectiveIconOnly, size]);

    const iconSizeMap: Record<Exclude<ButtonSize, 'icon'>, number> = { xs: 14, sm: 16, md: 18, lg: 20 };
    const iconSize = size === 'icon' ? 20 : (iconSizeMap[size as Exclude<ButtonSize, 'icon'>] ?? 18);

    const widthClass = fullWidth ? 'w-full' : '';

    const orderClasses = useMemo(() => {
      if (!icon || !children || loading || effectiveIconOnly) return { icon: '', slot: '' };
      return iconPosition === 'left'
        ? { icon: 'order-first', slot: 'order-last' }
        : { icon: 'order-last', slot: 'order-first' };
    }, [icon, children, loading, effectiveIconOnly, iconPosition]);

    const handleClick = useCallback((event: React.MouseEvent<HTMLButtonElement>) => {
      if (disabled || loading) {
        event.preventDefault();
        return;
      }
      onClick?.(event);
    }, [disabled, loading, onClick]);

    return (
      <button
        ref={ref}
        disabled={disabled || loading}
        className={`${baseClasses} ${variantClasses} ${sizeClasses} ${widthClass} ${className}`}
        onClick={handleClick}
        {...props}
      >
        {loading ? (
          <>
            <Icon name="Loader" size={iconSize} className={`animate-spin ${iconClass || ''}`} />
            {children && !effectiveIconOnly && (
              <span className={`${orderClasses.slot} opacity-70`}>{children}</span>
            )}
          </>
        ) : (
          <>
            {icon && (
              <Icon name={icon} size={iconSize} className={`${orderClasses.icon} ${iconClass || ''}`} />
            )}
            {children && !effectiveIconOnly && (
              <span className={orderClasses.slot}>
                {children}
              </span>
            )}
          </>
        )}
      </button>
    );
  }
);

Button.displayName = 'Button';

export { Button };
export default Button;
