// dam/frontend/src/components/track/TagInput.vue
<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps<{
  tags: string[]
  label: string
  placeholder?: string
}>()

const emit = defineEmits<{
  'update:tags': [tags: string[]]
}>()

const inputValue = ref('')

const addTag = () => {
  const tag = inputValue.value.trim()
  if (tag && !props.tags.includes(tag)) {
    emit('update:tags', [...props.tags, tag])
    inputValue.value = ''
  }
}

const removeTag = (index: number) => {
  const newTags = [...props.tags]
  newTags.splice(index, 1)
  emit('update:tags', newTags)
}

const handleKeydown = (e: KeyboardEvent) => {
  if (e.key === 'Enter') {
    e.preventDefault()
    addTag()
  }
}
</script>

<template>
  <div class="space-y-1.5">
    <label class="block text-xs font-medium text-text-muted">{{ label }}</label>

    <!-- Tags display -->
    <div v-if="tags.length > 0" class="flex flex-wrap gap-1.5 mb-1.5">
      <span
        v-for="(tag, index) in tags"
        :key="index"
        class="inline-flex items-center gap-1 px-2 py-0.5 text-xs rounded bg-primary/20 text-primary"
      >
        {{ tag }}
        <button
          @click="removeTag(index)"
          class="hover:text-primary-dark"
          aria-label="Remove tag"
        >
          <MdiClose class="w-3 h-3" />
        </button>
      </span>
    </div>

    <!-- Input -->
    <div class="flex gap-1.5">
      <input
        v-model="inputValue"
        @keydown="handleKeydown"
        type="text"
        :placeholder="placeholder || 'Add tag...'"
        class="flex-1 px-2 py-1.5 text-xs border rounded-md bg-background border-border text-text-primary placeholder-text-muted focus:outline-none focus:ring-1 focus:ring-primary"
      />
      <button
        @click="addTag"
        class="px-3 py-1.5 text-xs font-medium rounded-md bg-primary text-text-inverse hover:bg-primary-dark"
      >
        Add
      </button>
    </div>
  </div>
</template>

// crud-starter-pickard-apps/crud-app-sqlite-tanstack-shadcn/frontend/src/components/common/TagInput.tsx
import React, { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { X } from 'lucide-react';
import { cn } from '@/lib/utils';

interface TagInputProps {
  tags: string[];
  onTagsChange: (tags: string[]) => void;
  placeholder?: string;
  className?: string;
}

export function TagInput({ tags, onTagsChange, placeholder, className }: TagInputProps) {
  const [inputValue, setInputValue] = useState('');

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value);
  };

  const handleInputKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault();
      addTag();
    }
  };

  const addTag = () => {
    const newTag = inputValue.trim();
    if (newTag && !tags.includes(newTag)) {
      onTagsChange([...tags, newTag]);
    }
    setInputValue('');
  };

  const removeTag = (tagToRemove: string) => {
    onTagsChange(tags.filter(tag => tag !== tagToRemove));
  };

  return (
    <div className={cn('w-full', className)}>
      <div className="flex flex-wrap gap-2 mb-2">
        {tags.map(tag => (
          <Badge key={tag} variant="secondary">
            {tag}
            <button
              type="button"
              className="ml-2 rounded-full outline-none ring-offset-background focus:ring-2 focus:ring-ring focus:ring-offset-2"
              onClick={() => removeTag(tag)}
            >
              <X className="h-3 w-3 text-muted-foreground hover:text-foreground" />
            </button>
          </Badge>
        ))}
      </div>
      <div className="flex gap-2">
        <Input
          type="text"
          value={inputValue}
          onChange={handleInputChange}
          onKeyDown={handleInputKeyDown}
          placeholder={placeholder || "Add a tag and press Enter"}
        />
        <Button type="button" variant="outline" onClick={addTag}>
          Add
        </Button>
      </div>
    </div>
  );
}
