// crud-starter-pickard-apps/react/crud-app-sqlite-tanstack-shadcn/frontend/src/pages/AboutPage.tsx
export default function AboutPage() {
  return (
    <div className="p-4 bg-surface rounded-card">
      <h1 className="text-size-xl font-bold mb-4">About This Application</h1>
      <p>
        This is a modern, responsive React frontend for managing items, now refactored to use the full TanStack suite:
      </p>
      <ul className="list-disc list-inside my-4 space-y-2">
        <li><strong>TanStack Query</strong> for server state management.</li>
        <li><strong>TanStack Router</strong> for type-safe client-side routing.</li>
        <li><strong>TanStack Form</strong> for performant and type-safe forms.</li>
        <li><strong>Zustand</strong> for global UI state.</li>
        <li><strong>Tailwind CSS v4</strong> for styling.</li>
      </ul>
    </div>
  );
}

// crud-starter-pickard-apps/svelte/crud-app-sqlite-tanstack-shadcn-svelte-kit/src/lib/pages/AboutPage.svelte
<!-- src/lib/pages/AboutPage.svelte -->
<script lang="ts">
  import MainLayout from '$lib/components/layout/layout/MainLayout.svelte';
</script>

<MainLayout>
  <div class="space-y-6">
    <header>
      <h1 class="font-bold text-size-3xl">About This Application</h1>
    </header>

    <div class="p-6 border rounded-lg bg-surface border-border">
      <p class="mb-4 text-text-secondary">
        This is a modern, responsive Svelte 5 frontend for managing items.
      </p>

      <h2 class="mb-3 font-semibold text-size-xl">Core Technologies Used:</h2>

      <ul class="space-y-2 list-disc list-inside text-text-secondary">
        <li>
          <span class="font-medium text-text-primary">Svelte 5:</span>
          For building a reactive and performant user interface with Runes.
        </li>
        <li>
          <span class="font-medium text-text-primary">TanStack Query (Svelte Query):</span>
          Manages all server state.
        </li>
        <li>
          <span class="font-medium text-text-primary">shadcn-svelte:</span>
          UI Component library.
        </li>
        <li>
          <span class="font-medium text-text-primary">Tailwind CSS v4:</span>
          Styling.
        </li>
      </ul>
</div>
  </MainLayout>
