// crud-starter-pickard-apps/react/crud-app-sqlite-tanstack-shadcn/frontend/src/pages/ItemDetailPage.tsx
import { Link } from '@tanstack/react-router';

export default function ItemDetailPage() {
    // For now, we'll use a placeholder since the router API might be different
    const item = {
        name: 'Sample Item',
        categories: ['sample-category'],
        text: 'This is a sample item description.',
        tags: ['sample', 'demo']
    };

    return (
        <div className="p-4 bg-surface rounded-card">
            <Link to="/" className="text-primary hover:underline mb-4 inline-block">&larr; Back to all items</Link>
            <h1 className="text-size-xl font-bold mb-2">{item.name}</h1>
            <p className="text-text-secondary mb-4">Category: {item.categories[0]}</p>
            <div className="prose dark:prose-invert">
                <p>{item.text}</p>
            </div>
            <div className="flex gap-2 mt-4">
                {item.tags.map((tag: string) => (
                    <span key={tag} className="tag-sm bg-surface-hover text-text-secondary rounded-button">{tag}</span>
                ))}
            </div>
        </div>
    );
}

// crud-starter-pickard-apps/svelte/crud-app-sqlite-tanstack-shadcn-svelte-kit/src/lib/pages/ItemDetailPage.svelte
<script lang="ts">
  import { useItemDetail } from '$lib/api/itemsQuery';
  import { formatDate } from '$lib/utils/helpers';
  import type { Item } from '$lib/types';

  export let categorySlug: string;
  export let itemSlug: string;

  const { data: item, isLoading, error } = useItemDetail(() => categorySlug, () => itemSlug);
</script>

<div class="container mx-auto p-fluid-6">
  <a href="/" class="mb-4 inline-block text-primary hover:underline">
    ← Back
  </a>

  {#if isLoading}
    <div>Loading...</div>
  {:else if error}
    <div>Error: {error.message}</div>
  {:else if item}
    <div class="bg-surface rounded-card p-card">
      <h1 class="mb-4 font-bold text-size-2xl">{item.name}</h1>
      <p class="mb-4 text-text-secondary">{item.text}</p>
      <div class="flex gap-2 mb-4">
        <span class="tag-priority-{item.priority}">{item.priority}</span>
        {#if item.isCompleted}
          <span class="tag-sm bg-success-light">Completed</span>
        {/if}
      </div>
      <div class="text-size-sm text-text-muted">
        <p>Created: {formatDate(item.createdAt)}</p>
        <p>Updated: {formatDate(item.updatedAt)}</p>
      </div>
    </div>
  {/if}
</div>
