// crud-starter-pickard-apps/vue/crud-app-sqlite-tanstack-shadcn-nuxt/components/layout/TopBar.vue
<script setup lang="ts">
const route = useRoute();
</script>

<template>
  <header class="flex items-center justify-end pb-4 mb-4 border-b border-border">
    <nav class="flex items-center gap-4">
      <NuxtLink 
        to="/" 
        :class="route.path === '/' ? 'text-primary font-bold' : 'text-text-secondary hover:text-text-primary'"
      >
        Home
      </NuxtLink>
      <NuxtLink 
        to="/about" 
        :class="route.path === '/about' ? 'text-primary font-bold' : 'text-text-secondary hover:text-text-primary'"
      >
        About
      </NuxtLink>
    </nav>
  </header>
</template>

// crud-starter-pickard-apps/svelte/crud-app-sqlite-tanstack-shadcn-svelte-vite/src/lib/components/layout/TopBar.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  export let currentPath: string;

  const dispatch = createEventDispatcher<{ navigate: string }>();

  function navigate(path: string) {
    // Dispatch navigate event to parent
    dispatch('navigate', path);
  }
</script>

<header class="flex justify-end items-center pb-4 mb-4 border-b border-border">
  <nav class="flex items-center gap-4">
    <button 
      onclick={() => navigate('/')}
      class={currentPath === '/' ? 'text-primary font-bold' : 'text-text-secondary hover:text-text-primary'}
    >
      Home
    </button>
    <button 
      onclick={() => navigate('/about')}
      class={currentPath === '/about' ? 'text-primary font-bold' : 'text-text-secondary hover:text-text-primary'}
    >
      About
    </button>
  </nav>
</header>
