// crud-starter-pickard-apps/svelte/crud-app-sqlite-tanstack-shadcn-svelte-vite/src/App.svelte
<!-- src/App.svelte -->
<script lang="ts">
  import './app.css';
  import { QueryClientProvider } from '@tanstack/svelte-query';
  import { Toaster } from 'svelte-sonner';
  import { createAppQueryClient } from '$lib/api/itemsQuery';
  import Router from '$lib/router/Router.svelte';
  import { useThemeUpdater } from '$lib/utils/themeUpdater.svelte';

  const queryClient = createAppQueryClient();

  useThemeUpdater();
</script>

<main class="min-h-screen bg-background text-foreground">
  <QueryClientProvider client={queryClient}>
    <Toaster position="top-right" richColors />
    <Router />
  </QueryClientProvider>
</main>

// crud-starter-pickard-apps/vue/crud-app-sqlite-tanstack-shadcn-vue/src/App.vue
<script setup lang="ts">
import { RouterView } from 'vue-router';
import { Toaster } from 'vue-sonner';  
import 'vue-sonner/style.css';  
import { useThemeUpdater } from '@/composables/useThemeUpdater';

useThemeUpdater();
</script>

<template>
  <div class="min-h-screen bg-background text-foreground">
    <Toaster position="top-right" richColors />
    <RouterView />
  </div>
</template>
