// crud-starter-pickard-apps/svelte/crud-app-sqlite-tanstack-shadcn-svelte-kit/src/lib/components/layout/TopBar.svelte
<script lang="ts">
  // Received from +layout.svelte via $page store
  let { currentPath = '/' } = $props();
</script>

<header class="flex items-center justify-end pb-4 mb-4 border-b border-border">
  <nav class="flex items-center gap-4">
    <a 
      href="/"
      class={currentPath === '/' ? 'text-primary font-bold' : 'text-text-secondary hover:text-text-primary'}
    >
      Home
    </a>
    <a 
      href="/about"
      class={currentPath.startsWith('/about') ? 'text-primary font-bold' : 'text-text-secondary hover:text-text-primary'}
    >
      About
    </a>
  </nav>
</header>

// crud-starter-pickard-apps/vue/crud-app-sqlite-tanstack-shadcn-nuxt/components/layout/TopBar.vue
<script setup lang="ts">
const route = useRoute();
</script>

<template>
  <header class="flex items-center justify-end pb-4 mb-4 border-b border-border">
    <nav class="flex items-center gap-4">
      <NuxtLink 
        to="/" 
        :class="route.path === '/' ? 'text-primary font-bold' : 'text-text-secondary hover:text-text-primary'"
      >
        Home
      </NuxtLink>
      <NuxtLink 
        to="/about" 
        :class="route.path === '/about' ? 'text-primary font-bold' : 'text-text-secondary hover:text-text-primary'"
      >
        About
      </NuxtLink>
    </nav>
  </header>
</template>
