// crud-starter-pickard-apps/svelte/crud-app-sqlite-tanstack-shadcn-svelte-kit/src/lib/pages/AboutPage.svelte
<!-- src/lib/pages/AboutPage.svelte -->
<script lang="ts">
  import MainLayout from '$lib/components/layout/layout/MainLayout.svelte';
</script>

<MainLayout>
  <div class="space-y-6">
    <header>
      <h1 class="font-bold text-size-3xl">About This Application</h1>
    </header>

    <div class="p-6 border rounded-lg bg-surface border-border">
      <p class="mb-4 text-text-secondary">
        This is a modern, responsive Svelte 5 frontend for managing items.
      </p>

      <h2 class="mb-3 font-semibold text-size-xl">Core Technologies Used:</h2>

      <ul class="space-y-2 list-disc list-inside text-text-secondary">
        <li>
          <span class="font-medium text-text-primary">Svelte 5:</span>
          For building a reactive and performant user interface with Runes.
        </li>
        <li>
          <span class="font-medium text-text-primary">TanStack Query (Svelte Query):</span>
          Manages all server state.
        </li>
        <li>
          <span class="font-medium text-text-primary">shadcn-svelte:</span>
          UI Component library.
        </li>
        <li>
          <span class="font-medium text-text-primary">Tailwind CSS v4:</span>
          Styling.
        </li>
      </ul>
</div>
  </MainLayout>

// crud-starter-pickard-apps/vue/crud-app-sqlite-tanstack-shadcn-vue/src/pages/AboutPage.vue
<script setup lang="ts">
import MainLayout from '@/layouts/MainLayout.vue';
</script>

<template>
  <MainLayout>
    <div class="space-y-6">
      <header>
        <h1 class="font-bold text-size-3xl">About This Application</h1>
      </header>
      
      <div class="p-6 border rounded-lg bg-surface border-border">
        <p class="mb-4 text-text-secondary">
          This is a modern, responsive Vue frontend for managing items, built to serve as a clean and robust boilerplate. It leverages the full power of the TanStack suite and modern tooling for a superior developer experience and a fully type-safe workflow.
        </p>
        
        <h2 class="mb-3 font-semibold text-size-xl">Core Technologies Used:</h2>
        
        <ul class="space-y-2 list-disc list-inside text-text-secondary">
          <li>
            <strong class="font-medium text-text-primary">Vue 3:</strong> For building a reactive and performant user interface with the Composition API.
          </li>
          <li>
            <strong class="font-medium text-text-primary">TanStack Query (Vue Query):</strong> Manages all server state, handling data fetching, caching, and synchronization effortlessly.
          </li>
          <li>
            <strong class="font-medium text-text-primary">TanStack Form (Vue Form):</strong> Ensures performant and 100% type-safe forms from validation to submission.
          </li>
          <li>
            <strong class="font-medium text-text-primary">Pinia:</strong> Provides simple and type-safe global state management for client-side UI state.
          </li>
           <li>
            <strong class="font-medium text-text-primary">shadcn-vue:</strong> A collection of beautifully designed, accessible, and unstyled components that are adapted to our custom design system.
          </li>
          <li>
            <strong class="font-medium text-text-primary">Tailwind CSS v4:</strong> Powers styling with a "CSS-first" approach, using a custom, token-based, and fluidly responsive design system.
          </li>
        </ul>
      </div>
    </div>
  </MainLayout>
</template>
