// crud-app-sqlite-tanstack/frontend/src/pages/ItemPage.tsx
import { useState } from 'react';
import { useGetItemTree } from '@/hooks/useItemsApi';
import { useItemFilters } from '@/hooks/useItemFilters';
import ItemItem from '@/components/items/ItemItem';
import { useToggleItemCompletion, useDeleteItem } from '@/hooks/useItemsApi';

export default function ItemPage() {
  const { data: itemTree = {}, isLoading, error } = useGetItemTree();
  const [searchQuery, setSearchQuery] = useState('');
  
  // The filter hook can remain as it is pure logic
  const { filteredItemTree, totalFilteredItems } = useItemFilters(itemTree, {
      searchQuery,
      selectedPriority: 'all',
      showCompleted: true,
      selectedTags: [],
  });
  
  const toggleItemCompletion = useToggleItemCompletion();
  const deleteItemMutation = useDeleteItem();

  if (isLoading) return <div>Loading items...</div>;
  if (error) return <div className="text-danger">Error: {error.message}</div>;

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-4">
        <input
          type="text"
          placeholder="Search items..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="px-3 py-2 border border-border rounded-md"
        />
      </div>
      <p className="text-text-muted">{totalFilteredItems} items found.</p>
      <div className="space-y-6">
        {Object.entries(filteredItemTree).map(([category, items]) => (
          <div key={category}>
            <h2 className="text-size-lg font-bold mb-2 capitalize border-b border-border pb-1">
              {category.replace(/-/g, ' ')}
            </h2>
            <div className="space-y-2">
              {items.map(item => (
                <ItemItem
                  key={item.id}
                  item={item}
                  onToggleComplete={() => toggleItemCompletion(item)}
                  onEdit={() => {}} // Placeholder for now
                  onDelete={() => deleteItemMutation.mutate({ categorySlug: category, itemSlug: item.slug })}
                />
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// crud-starter-pickard-apps/vue/crud-app-sqlite-tanstack-shadcn-vue/src/pages/ItemPage.vue
<script setup lang="ts">
import MainLayout from '@/layouts/MainLayout.vue';
import { useItemTree } from '@/composables/useItemsApi';
import { useItemFilters } from '@/composables/useItemFilters';
import FilterBar from '@/components/layout/FilterBar.vue';
import ItemItem from '@/components/items/ItemItem.vue';
import ItemForm from '@/components/items/ItemForm.vue';

const { data: itemTree, isLoading, error } = useItemTree();

const filters = ref({
  searchQuery: '',
  selectedPriority: 'all' as const,
  showCompleted: true,
  selectedTags: [],
});

const { filteredItemTree, allTags, hasActiveFilters, clearFilters } = useItemFilters(
  computed(() => itemTree.value || {}),
  filters
);

const isFormOpen = ref(false);
</script>

<template>
  <MainLayout>
    <header class="mb-6">
      <h1 class="mb-2 font-bold text-size-3xl">Items</h1>
      <!-- The "Add New Item" button is now in the sidebar -->
    </header>

    <FilterBar
      v-model:search="filters.searchQuery"
      v-model:priority="filters.selectedPriority"
      v-model:showCompleted="filters.showCompleted"
      v-model:selectedTags="filters.selectedTags"
      :all-tags="allTags"
      :has-active-filters="hasActiveFilters"
      @clear="clearFilters"
    />

    <div v-if="isLoading">Loading...</div>
    <div v-else-if="error">Error: {{ error.message }}</div>
    <div v-else class="mt-6 space-y-8">
      <section v-for="(items, category) in filteredItemTree" :key="category">
        <div class="flex items-center gap-2 mb-4">
          <h2 class="font-semibold capitalize text-size-xl">{{ category }}</h2>
          <span class="text-sm text-text-muted">({{ items.length }})</span>
        </div>
        <div class="grid gap-4">
          <ItemItem
            v-for="item in items"
            :key="item.id"
            :item="item"
          />
        </div>
      </section>
      <div v-if="Object.keys(filteredItemTree).length === 0 && !isLoading" class="py-10 text-center text-text-muted">
        <p>No items found.</p>
        <p v-if="hasActiveFilters">Try adjusting your filters.</p>
      </div>
    </div>

    <!-- The ItemForm will be triggered from the sidebar -->
    <ItemForm
      v-if="isFormOpen"
      @close="isFormOpen = false"
    />
  </MainLayout>
</template>
