// crud-starter-pickard-apps/svelte/crud-app-sqlite-tanstack-shadcn-svelte-vite/src/lib/pages/ItemPage.svelte
<script lang="ts">
  import MainLayout from '$lib/components/layout/MainLayout.svelte';
  import { useItemTree } from '$lib/api/itemsQuery';
  import { useItemFilters } from '$lib/utils/useItemFilters';
  import FilterBar from '$lib/components/layout/FilterBar.svelte';
  import ItemItem from '$lib/components/items/ItemItem.svelte';
  import ItemForm from '$lib/components/items/ItemForm.svelte';
  import { uiStore } from '$lib/stores/uiStore';
  import { Button } from '$lib/components/ui/button';

  const itemTreeQuery = useItemTree();

  let filters = {
    searchQuery: '',
    selectedPriority: 'all' as const,
    showCompleted: true,
    selectedTags: [] as string[],
  };

  $: filterResults = useItemFilters($itemTreeQuery.data || {}, filters);
  $: filteredItemTree = filterResults.filteredItemTree;
  $: allTags = filterResults.allTags;
  $: hasActiveFilters = filterResults.hasActiveFilters;

  function clearFilters() {
    filters = {
      searchQuery: '',
      selectedPriority: 'all',
      showCompleted: true,
      selectedTags: [],
    };
  }
</script>

<MainLayout on:navigate>
  <header class="mb-6">
    <h1 class="mb-2 font-bold text-size-3xl">Items</h1>
    <!-- The main "Add New Item" button remains in the sidebar -->
  </header>

  <FilterBar
    bind:search={filters.searchQuery}
    bind:priority={filters.selectedPriority}
    bind:showCompleted={filters.showCompleted}
    bind:selectedTags={filters.selectedTags}
    {allTags}
    {hasActiveFilters}
    on:clear={clearFilters}
  />

  {#if $itemTreeQuery.isLoading}
    <div>Loading...</div>
  {:else if $itemTreeQuery.error}
    <div>Error: {$itemTreeQuery.error.message}</div>
  {:else}
    <div class="mt-6 space-y-8">
      {#each Object.entries(filteredItemTree) as [category, items]}
        <section>
          <div class="flex items-center gap-2 mb-4">
            <h2 class="font-semibold capitalize text-size-xl">{category}</h2>
            <span class="text-sm text-text-muted">({items.length})</span>
            <!-- Add "+" button here -->
            <Button 
              variant="ghost" 
              size="icon-sm" 
              onclick={() => uiStore.openForm(undefined, category)}
            >
              <icon-lucide-plus class="w-4 h-4"></icon-lucide-plus>
            </Button>
          </div>
          <div class="grid gap-4">
            {#each items as item (item.id)}
              <ItemItem {item} />
            {/each}
          </div>
        </section>
      {/each}
      {#if Object.keys(filteredItemTree).length === 0 && !$itemTreeQuery.isLoading}
        <div class="py-10 text-center text-text-muted">
          <p>No items found.</p>
          {#if hasActiveFilters}
            <p>Try adjusting your filters.</p>
          {/if}
        </div>
      {/if}
    </div>
  {/if}

  <!-- The ItemForm is now aware of pre-selected category -->
  {#if $uiStore.isFormOpen}
    <ItemForm on:close={() => uiStore.closeForm()} />
  {/if}
</MainLayout>

// crud-starter-pickard-apps/vue/crud-app-sqlite-tanstack-shadcn-vue/src/pages/ItemPage.vue
<script setup lang="ts">
import MainLayout from '@/layouts/MainLayout.vue';
import { useItemTree } from '@/composables/useItemsApi';
import { useItemFilters } from '@/composables/useItemFilters';
import FilterBar from '@/components/layout/FilterBar.vue';
import ItemItem from '@/components/items/ItemItem.vue';
import ItemForm from '@/components/items/ItemForm.vue';
import { useUiStore } from '@/stores/uiStore';
import { Button } from '@/components/ui/button';

const { data: itemTree, isLoading, error } = useItemTree();
const uiStore = useUiStore();

const filters = ref({
  searchQuery: '',
  selectedPriority: 'all' as const,
  showCompleted: true,
  selectedTags: [],
});

const { filteredItemTree, allTags, hasActiveFilters, clearFilters } = useItemFilters(
  computed(() => itemTree.value || {}),
  filters
);
</script>

<template>
  <MainLayout>
    <header class="mb-6">
      <h1 class="mb-2 font-bold text-size-3xl">Items</h1>
      <!-- The main "Add New Item" button remains in the sidebar -->
    </header>

    <FilterBar
      v-model:search="filters.searchQuery"
      v-model:priority="filters.selectedPriority"
      v-model:showCompleted="filters.showCompleted"
      v-model:selectedTags="filters.selectedTags"
      :all-tags="allTags"
      :has-active-filters="hasActiveFilters"
      @clear="clearFilters"
    />

    <div v-if="isLoading">Loading...</div>
    <div v-else-if="error">Error: {{ error.message }}</div>
    <div v-else class="mt-6 space-y-8">
      <section v-for="(items, category) in filteredItemTree" :key="category">
        <div class="flex items-center gap-2 mb-4">
          <h2 class="font-semibold capitalize text-size-xl">{{ category }}</h2>
          <span class="text-sm text-text-muted">({{ items.length }})</span>
          <!-- Add "+" button here -->
          <Button variant="ghost" size="icon-sm" @click="uiStore.openForm(undefined, category)">
            <icon-lucide-plus class="w-4 h-4" />
          </Button>
        </div>
        <div class="grid gap-4">
          <ItemItem
            v-for="item in items"
            :key="item.id"
            :item="item"
          />
        </div>
      </section>
      <div v-if="Object.keys(filteredItemTree).length === 0 && !isLoading" class="py-10 text-center text-text-muted">
        <p>No items found.</p>
        <p v-if="hasActiveFilters">Try adjusting your filters.</p>
      </div>
    </div>

    <!-- The ItemForm is now aware of pre-selected category -->
    <ItemForm
      v-if="uiStore.isFormOpen"
      @close="uiStore.closeForm"
    />
  </MainLayout>
</template>
