// dam/frontend/src/components/track/TagInput.vue
<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps<{
  tags: string[]
  label: string
  placeholder?: string
}>()

const emit = defineEmits<{
  'update:tags': [tags: string[]]
}>()

const inputValue = ref('')

const addTag = () => {
  const tag = inputValue.value.trim()
  if (tag && !props.tags.includes(tag)) {
    emit('update:tags', [...props.tags, tag])
    inputValue.value = ''
  }
}

const removeTag = (index: number) => {
  const newTags = [...props.tags]
  newTags.splice(index, 1)
  emit('update:tags', newTags)
}

const handleKeydown = (e: KeyboardEvent) => {
  if (e.key === 'Enter') {
    e.preventDefault()
    addTag()
  }
}
</script>

<template>
  <div class="space-y-1.5">
    <label class="block text-xs font-medium text-text-muted">{{ label }}</label>

    <!-- Tags display -->
    <div v-if="tags.length > 0" class="flex flex-wrap gap-1.5 mb-1.5">
      <span
        v-for="(tag, index) in tags"
        :key="index"
        class="inline-flex items-center gap-1 px-2 py-0.5 text-xs rounded bg-primary/20 text-primary"
      >
        {{ tag }}
        <button
          @click="removeTag(index)"
          class="hover:text-primary-dark"
          aria-label="Remove tag"
        >
          <MdiClose class="w-3 h-3" />
        </button>
      </span>
    </div>

    <!-- Input -->
    <div class="flex gap-1.5">
      <input
        v-model="inputValue"
        @keydown="handleKeydown"
        type="text"
        :placeholder="placeholder || 'Add tag...'"
        class="flex-1 px-2 py-1.5 text-xs border rounded-md bg-background border-border text-text-primary placeholder-text-muted focus:outline-none focus:ring-1 focus:ring-primary"
      />
      <button
        @click="addTag"
        class="px-3 py-1.5 text-xs font-medium rounded-md bg-primary text-text-inverse hover:bg-primary-dark"
      >
        Add
      </button>
    </div>
  </div>
</template>

// crud-app-sqlite-tanstack-shadcn/frontend/src/components/common/TagInput.tsx
import { X } from 'lucide-react';
import { useState, KeyboardEvent } from 'react';

interface TagInputProps {
  value: string[];
  onChange: (tags: string[]) => void;
  placeholder?: string;
  className?: string;
}

export function TagInput({ 
  value = [], 
  onChange, 
  placeholder = 'Add tags...',
  className = ''
}: TagInputProps) {
  const [inputValue, setInputValue] = useState('');

  const addTag = (tag: string) => {
    const trimmed = tag.trim();
    if (trimmed && !value.includes(trimmed)) {
      onChange([...value, trimmed]);
      setInputValue('');
    }
  };

  const removeTag = (tagToRemove: string) => {
    onChange(value.filter(t => t !== tagToRemove));
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      addTag(inputValue);
    } else if (e.key === 'Backspace' && !inputValue && value.length > 0) {
      // Remove last tag on backspace when input is empty
      removeTag(value[value.length - 1]);
    } else if (e.key === ',') {
      e.preventDefault();
      addTag(inputValue);
    }
  };

  const handleBlur = () => {
    if (inputValue.trim()) {
      addTag(inputValue);
    }
  };

  return (
    <div className={`flex flex-wrap gap-2 p-2 border border-border rounded-input bg-surface focus-within:border-border-focus focus-within:shadow-[0_0_0_1px_var(--color-border-focus)] transition-all ${className}`}>
      {value.map((tag) => (
        <span
          key={tag}
          className="border tag-sm bg-primary/10 text-primary border-primary/20 rounded-button"
        >
          {tag}
          <button
            type="button"
            onClick={() => removeTag(tag)}
            className="transition-colors hover:text-danger"
            aria-label={`Remove ${tag}`}
          >
            <X size={12} />
          </button>
        </span>
      ))}
      <input
        type="text"
        value={inputValue}
        onChange={(e) => setInputValue(e.target.value)}
        onKeyDown={handleKeyDown}
        onBlur={handleBlur}
        placeholder={value.length === 0 ? placeholder : ''}
    className="flex-1 min-w-[80px] bg-transparent border-0 outline-none focus:ring-0 focus-visible:ring-0 focus-visible:outline-none text-size-sm py-0 px-0 text-text-primary placeholder:text-text-muted"
      />
    </div>
  );
}

export default TagInput;
