// crud-starter-pickard-apps/react/crud-app-sqlite-tanstack-shadcn-next/hooks/useItemFilters.ts
import { useMemo, useState } from 'react';
import type { Item, Priority } from '@/types';
import { ItemTree } from '@/lib/api/itemApi';

interface FilterOptions {
  searchQuery: string;
  selectedPriority: 'all' | Priority;
  showCompleted: boolean;
  selectedTags: string[];
}

export function useItemFilters(itemTree: ItemTree) {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedPriority, setSelectedPriority] = useState<'all' | Priority>('all');
  const [showCompleted, setShowCompleted] = useState(true);
  const [selectedTags, setSelectedTags] = useState<string[]>([]);

  const allTags = useMemo(() => {
    const tags = new Set<string>();
    Object.values(itemTree).forEach(items => {
      items.forEach(item => {
        item.tags?.forEach(tag => tags.add(tag));
      });
    });
    return Array.from(tags).sort();
  }, [itemTree]);

  const hasActiveFilters = useMemo(() => {
    return searchQuery.trim() !== '' ||
           selectedPriority !== 'all' ||
           !showCompleted ||
           selectedTags.length > 0;
  }, [searchQuery, selectedPriority, showCompleted, selectedTags]);

  const filteredItemTree = useMemo(() => {
    const filtered: Record<string, Item[]> = {};
    
    Object.entries(itemTree).forEach(([categoryName, items]) => {
      const filteredItems = items.filter(item => {
        // Search filter
        if (searchQuery.trim()) {
          const query = searchQuery.toLowerCase();
          const matchesSearch = 
            item.name.toLowerCase().includes(query) ||
            item.text.toLowerCase().includes(query) ||
            item.tags?.some(tag => tag.toLowerCase().includes(query));
          if (!matchesSearch) return false;
        }

        // Priority filter
        if (selectedPriority !== 'all' && item.priority !== selectedPriority) {
          return false;
        }

        // Completion status filter
        if (!showCompleted && item.isCompleted) {
          return false;
        }

        // Tag filter
        if (selectedTags.length > 0) {
          const hasSelectedTag = selectedTags.some(tag => 
            item.tags?.includes(tag)
          );
          if (!hasSelectedTag) return false;
        }

        return true;
      });
      
      if (filteredItems.length > 0) {
        filtered[categoryName] = filteredItems;
      }
    });
    
    return filtered;
  }, [itemTree, searchQuery, selectedPriority, showCompleted, selectedTags]);

  const totalItems = useMemo(() => {
    return Object.values(itemTree).reduce((total, items) => total + items.length, 0);
  }, [itemTree]);

  const totalFilteredItems = useMemo(() => {
    return Object.values(filteredItemTree).reduce((total, items) => total + items.length, 0);
  }, [filteredItemTree]);

  return {
    searchQuery, setSearchQuery,
    selectedPriority, setSelectedPriority,
    showCompleted, setShowCompleted,
    selectedTags, setSelectedTags,
    allTags,
    hasActiveFilters,
    filteredItemTree,
    totalItems,
    totalFilteredItems,
  };
}

// simple/solid-simple-crud/frontend/src/hooks/useItemFilters.ts
// frontends/solid/src/hooks/useItemFilters.ts
import { createMemo } from 'solid-js';
import type { Item, Priority, ItemTree } from '@/types';

interface FilterOptions {
  searchQuery: string;
  selectedPriority: 'all' | Priority;
  showCompleted: boolean;
  selectedTags: string[];
}

export function useItemFilters(itemTreeGetter: () => ItemTree, filtersAccessor: () => FilterOptions) {

  const itemTree = createMemo(() => {
    const tree = itemTreeGetter();
    return tree;
  });

  const _allTags = createMemo(() => { // Renamed to avoid conflict in return
    const tree = itemTree();
    const tags = new Set<string>();
    Object.values(tree).forEach(items => {
      items.forEach(item => {
        item.tags?.forEach(tag => tags.add(tag));
      });
    });
    return Array.from(tags).sort();
  });

  const _hasActiveFilters = createMemo(() => { // Renamed
    const currentFilters = filtersAccessor();
    return currentFilters.searchQuery.trim() !== '' ||
           currentFilters.selectedPriority !== 'all' ||
           currentFilters.showCompleted || // Corrected: showCompleted means filter is active if true
           currentFilters.selectedTags.length > 0;
  });

  const _filteredItemTree = createMemo(() => { // Renamed
    const tree = itemTree();
    const currentFilters = filtersAccessor();
    
    const filtered: Record<string, Item[]> = {};
    
    Object.entries(tree).forEach(([categoryName, items]) => {
      const filteredItems = items.filter(item => {
        if (currentFilters.searchQuery.trim()) {
          const query = currentFilters.searchQuery.toLowerCase();
          const matchesSearch = 
            item.name.toLowerCase().includes(query) ||
            (item.text && item.text.toLowerCase().includes(query)) ||
            item.tags?.some(tag => tag.toLowerCase().includes(query));
          if (!matchesSearch) return false;
        }

        if (currentFilters.selectedPriority !== 'all' && item.priority !== currentFilters.selectedPriority) {
          return false;
        }

        if (!currentFilters.showCompleted && item.isCompleted) {
          return false;
        }

        if (currentFilters.selectedTags.length > 0) {
          const hasSelectedTag = currentFilters.selectedTags.some(tag => 
            item.tags?.includes(tag)
          );
          if (!hasSelectedTag) return false;
        }

        return true;
      });
      
      if (filteredItems.length > 0) {
        filtered[categoryName] = filteredItems;
      }
    });
    
    return filtered;
  });

  const _totalItems = createMemo(() => { // Renamed
    return Object.values(itemTree()).reduce((total, items) => total + items.length, 0);
  });

  const _totalFilteredItems = createMemo(() => { // Renamed
    return Object.values(_filteredItemTree()).reduce((total, items) => total + items.length, 0);
  });

  // Return the accessors directly
  return {
    allTags: _allTags,
    hasActiveFilters: _hasActiveFilters,
    filteredItemTree: _filteredItemTree,
    totalItems: _totalItems,
    totalFilteredItems: _totalFilteredItems,
  };
}
