// crud-starter-pickard-apps/svelte/crud-app-sqlite-tanstack-shadcn-svelte-vite/src/lib/components/layout/AppSidebar.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import { Separator } from '$lib/components/ui/separator';
  import { uiStore } from '$lib/stores/uiStore';

  // These would eventually be props or come from a store
  let searchQuery = '';
  let allTags = ['project', 'personal', 'work']; // Example tags
  let selectedTags: string[] = [];

  function toggleTag(tag: string) {
    const index = selectedTags.indexOf(tag);
    if (index > -1) {
      selectedTags.splice(index, 1);
    } else {
      selectedTags.push(tag);
    }
  }
</script>

<aside class="flex flex-col p-4 border-r bg-surface border-border">
  <div class="p-2 mb-4">
    <h2 class="text-xl font-bold">TodoApp</h2>
  </div>

  <div class="flex-1 space-y-4">
    <!-- Search -->
    <div class="px-2">
      <Input bind:value={searchQuery} placeholder="Search tasks..." />
    </div>

    <Separator />

    <!-- Tags Section -->
    <div class="px-2">
      <h3 class="mb-2 text-sm font-semibold text-text-muted">Tags</h3>
      <div class="flex flex-wrap gap-2">
        {#each allTags as tag (tag)}
          <Button
            onclick={() => toggleTag(tag)}
            variant={selectedTags.includes(tag) ? 'default' : 'outline'}
            size="sm"
            class="rounded-full"
          >
            {tag}
          </Button>
        {/each}
      </div>
    </div>

    <!-- Add New Item Button -->
    <div class="px-2 mt-4">
      <Button class="w-full" onclick={() => uiStore.openForm()}>
        + Add Item
      </Button>
    </div>
  </div>

  <!-- Footer / Theme Toggle -->
  <div class="mt-auto">
    <Button variant="ghost" onclick={() => uiStore.toggleTheme()} class="justify-start w-full">
      {#if !$uiStore.isDark}
        <icon-lucide-sun class="w-4 h-4" />
      {:else}
        <icon-lucide-moon class="w-4 h-4" />
      {/if}
    </Button>
  </div>
</aside>

// crud-starter-pickard-apps/vue/crud-app-sqlite-tanstack-shadcn-vue/src/components/layout/AppSidebar.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Separator } from '@/components/ui/separator';
import { useUiStore } from '@/stores/uiStore';

// These would eventually be props or come from a store
const searchQuery = ref('');
const allTags = ref(['project', 'personal', 'work']); // Example tags
const selectedTags = ref<string[]>([]);

const uiStore = useUiStore();

const toggleTag = (tag: string) => {
  const index = selectedTags.value.indexOf(tag);
  if (index > -1) {
    selectedTags.value.splice(index, 1);
  } else {
    selectedTags.value.push(tag);
  }
};
</script>

<template>
  <aside class="flex flex-col p-4 border-r w-72 bg-surface border-border">
    <div class="p-2 mb-4">
      <h2 class="text-xl font-bold">TodoApp</h2>
    </div>

    <div class="flex-1 space-y-4">
      <!-- Search -->
      <div class="px-2">
        <Input v-model="searchQuery" placeholder="Search tasks..." />
      </div>

      <Separator />

      <!-- Tags Section -->
      <div class="px-2">
        <h3 class="mb-2 text-sm font-semibold text-text-muted">Tags</h3>
        <div class="flex flex-wrap gap-2">
          <Button
            v-for="tag in allTags"
            :key="tag"
            @click="toggleTag(tag)"
            :variant="selectedTags.includes(tag) ? 'default' : 'outline'"
            size="sm"
            class="rounded-full"
          >
            {{ tag }}
          </Button>
        </div>
      </div>

      <!-- Add New Item Button -->
      <div class="px-2 mt-4">
        <Button class="w-full" @click="uiStore.openForm()">
          + Add Item
        </Button>
      </div>
    </div>

    <!-- Footer / Theme Toggle -->
    <div class="mt-auto">
      <Button variant="ghost" @click="uiStore.toggleTheme()" class="justify-start w-full">
        <icon-lucide-sun v-if="!uiStore.isDark" class="w-4 h-4" />
        <icon-lucide-moon v-else class="w-4 h-4" />
      </Button>
    </div>
  </aside>
</template>
