// crud-app-sqlite-tanstack/frontend/src/components/layout/TopBar.tsx
import { Link } from '@tanstack/react-router';

export default function TopBar() {
  return (
    <header className="flex justify-end items-center pb-4 mb-4 border-b border-border">
            <nav className="flex items-center gap-4">
                 <Link to="/" className="text-text-secondary hover:text-text-primary" activeProps={{ className: 'text-primary font-bold' }}>
                    Home
                </Link>
                <Link to="/about" className="text-text-secondary hover:text-text-primary" activeProps={{ className: 'text-primary font-bold' }}>
                    About
                </Link>
            </nav>
        </header>
      );
}

// crud-starter-pickard-apps/vue/crud-app-sqlite-tanstack-shadcn-vue/src/components/layout/TopBar.vue
<script setup lang="ts">
import { RouterLink, useRoute } from 'vue-router';

const route = useRoute();
</script>

<template>
  <header class="flex justify-end items-center pb-4 mb-4 border-b border-border">
    <nav class="flex items-center gap-4">
      <RouterLink 
        to="/" 
        :class="route.path === '/' ? 'text-primary font-bold' : 'text-text-secondary hover:text-text-primary'"
      >
        Home
      </RouterLink>
      <RouterLink 
        to="/about" 
        :class="route.path === '/about' ? 'text-primary font-bold' : 'text-text-secondary hover:text-text-primary'"
      >
        About
      </RouterLink>
    </nav>
  </header>
</template>
