// crud-starter-pickard-apps/react/crud-app-sqlite-tanstack-shadcn-next/components/items/ItemItem.tsx
'use client';

import Link from 'next/link';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Pencil, Trash2, ExternalLink } from 'lucide-react';
import { Item } from '@/types';
import { formatDate } from '@/utils/helpers';
import { useItemsApi } from '@/hooks/useItemsApi';

interface ItemItemProps {
  item: Item;
  onEdit?: (item: Item) => void;
  showActions?: boolean;
}

export function ItemItem({ item, onEdit, showActions = true }: ItemItemProps) {
  const { deleteItemMutation } = useItemsApi();

  const handleDelete = async () => {
    if (window.confirm('Are you sure you want to delete this item?')) {
      deleteItemMutation.mutate(item.id);
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high':
        return 'bg-destructive text-destructive-foreground';
      case 'medium':
        return 'bg-warning text-warning-foreground';
      case 'low':
        return 'bg-success text-success-foreground';
      default:
        return 'bg-secondary text-secondary-foreground';
    }
  };

  return (
    <Card className="group hover:shadow-md transition-all duration-200 hover:-translate-y-1">
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between gap-3">
          <div className="flex-1 min-w-0">
            <h3 className="font-semibold text-lg leading-tight truncate group-hover:text-primary transition-colors">
              {item.title}
            </h3>
            <p className="text-sm text-muted-foreground mt-1 line-clamp-2">
              {item.description}
            </p>
          </div>
          <Badge className={`shrink-0 ${getPriorityColor(item.priority)}`}>
            {item.priority}
          </Badge>
        </div>
      </CardHeader>
      
      <CardContent className="pt-0">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4 text-sm text-muted-foreground">
            <span className="truncate max-w-[120px]">{item.category}</span>
            <span className="shrink-0">{formatDate(item.createdAt)}</span>
          </div>
          
          {showActions && (
            <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
              <Link href={`/items/${item.categorySlug}/${item.slug}`}>
                <Button variant="ghost" size="sm">
                  <ExternalLink className="size-4" />
                </Button>
              </Link>
              <Button 
                variant="ghost" 
                size="sm"
                onClick={() => onEdit?.(item)}
              >
                <Pencil className="size-4" />
              </Button>
              <Button 
                variant="ghost" 
                size="sm"
                onClick={handleDelete}
                disabled={deleteItemMutation.isPending}
              >
                <Trash2 className="size-4" />
              </Button>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
}

// crud-starter-pickard-apps/vue/crud-app-sqlite-tanstack-shadcn-vue/src/components/items/ItemItem.vue
<script setup lang="ts">
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { useUpdateItem, useDeleteItem } from '@/composables/useItemsApi';
import { formatDate } from '@/utils/helpers';
import type { Item } from '@/types';

const props = defineProps<{ item: Item }>();

const { mutate: updateItem } = useUpdateItem();
const { mutate: deleteItem } = useDeleteItem();

const toggleComplete = () => {
  updateItem({
    id: props.item.id,
    payload: { isCompleted: !props.item.isCompleted },
  });
};

const handleDelete = () => {
  if (confirm('Are you sure you want to delete this item?')) {
    deleteItem(props.item.id);
  }
};
</script>

<template>
  <Card :class="{ 'opacity-60': item.isCompleted }">
    <CardContent class="flex items-start gap-4 p-4">
      <Checkbox
        :checked="item.isCompleted"
        @update:checked="toggleComplete"
        class="mt-1"
      />
      <div class="flex-1">
        <div class="flex items-center justify-between">
            <h3 
              class="font-semibold text-size-lg"
              :class="{ 'line-through text-text-muted': item.isCompleted }"
            >
              {{ item.name }}
            </h3>
             <Badge :class="`tag-priority-${item.priority}`" variant="outline">
               {{ item.priority }}
            </Badge>
        </div>
        <p class="mb-3 text-text-secondary">{{ item.text }}</p>

        <div class="flex items-center justify-between">
            <p class="text-xs text-text-muted">{{ formatDate(item.createdAt) }}</p>
            <div class="flex gap-2">
                <Button size="sm" variant="ghost" @click="() => {}">
                    <icon-lucide-pencil class="w-4 h-4" />
                </Button>
                <Button size="sm" variant="destructive" @click="handleDelete">
                    <icon-lucide-trash-2 class="w-4 h-4" />
                </Button>
            </div>
        </div>

        <div class="flex gap-2 mt-3">
          <Badge v-for="tag in item.tags" :key="tag" variant="secondary">{{ tag }}</Badge>
        </div>
      </div>
    </CardContent>
  </Card>
</template>
